// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://muyiitnplujnauepbsqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11eWlpdG5wbHVqbmF1ZXBic3FxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NjIyMzYsImV4cCI6MjA2OTQzODIzNn0.RWc_fN23T3L5IwhRjLH_Wy0c2fI_K2-yOpO7ly63rsM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});